export const ADD_POKEMON = "ADD_POKEMON";
export const CATCH_POKEMON = "CATCH_POKEMON";
export const GET_CATCHED_FROM_STORAGE = "GET_CATCHED_FROM_STORAGE";
export const RELEASE_POKEMON = "RELEASE_POKEMON";
export const GET_INIT_POKEMONS = "GET_INIT_POKEMONS";
export const HANDLE_LOADING = "HANDLE_LOADING";
